theme: jekyll-theme-minimal
title: Topi Talikka
logo: https://cloud.topitalikka.fi/index.php/apps/files_sharing/publicpreview/Td6zp93bs4GzYif?x=2054&y=976&a=true&file=Fraktal_Topi_04_lowres.jpg&scalingup=0
